export interface ChapterSeed {
  subjectCode: string;
  name: string;
  number: number;
  syllabusTag: string;
}

export const CHAPTERS: ChapterSeed[] = [
  // ─── Physics — JEE ─────────────────────────────────────────────────────────
  { subjectCode: 'PHY', name: 'Physical World and Measurement', number: 1, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Kinematics', number: 2, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Laws of Motion', number: 3, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Work, Energy and Power', number: 4, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Rotational Motion', number: 5, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Gravitation', number: 6, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Properties of Solids and Liquids', number: 7, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Thermodynamics', number: 8, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Kinetic Theory of Gases', number: 9, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Oscillations and Waves', number: 10, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Electrostatics', number: 11, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Current Electricity', number: 12, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Magnetic Effects of Current and Magnetism', number: 13, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Electromagnetic Induction and Alternating Currents', number: 14, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Electromagnetic Waves', number: 15, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Optics', number: 16, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Dual Nature of Matter and Radiation', number: 17, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Atoms and Nuclei', number: 18, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Electronic Devices', number: 19, syllabusTag: 'JEE' },
  { subjectCode: 'PHY', name: 'Communication Systems', number: 20, syllabusTag: 'JEE' },

  // ─── Chemistry — JEE ───────────────────────────────────────────────────────
  { subjectCode: 'CHE', name: 'Some Basic Concepts of Chemistry', number: 1, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Structure of Atom', number: 2, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Classification of Elements and Periodicity', number: 3, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Chemical Bonding and Molecular Structure', number: 4, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'States of Matter', number: 5, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Thermodynamics', number: 6, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Equilibrium', number: 7, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Redox Reactions and Electrochemistry', number: 8, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Chemical Kinetics', number: 9, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Surface Chemistry', number: 10, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'General Principles and Processes of Isolation of Metals', number: 11, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Hydrogen', number: 12, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 's-Block Elements', number: 13, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'p-Block Elements', number: 14, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'd and f Block Elements', number: 15, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Coordination Compounds', number: 16, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Purification and Characterisation of Organic Compounds', number: 17, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Basic Principles of Organic Chemistry', number: 18, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Hydrocarbons', number: 19, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Organic Compounds Containing Halogens', number: 20, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Organic Compounds Containing Oxygen', number: 21, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Organic Compounds Containing Nitrogen', number: 22, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Polymers', number: 23, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Biomolecules', number: 24, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Chemistry in Everyday Life', number: 25, syllabusTag: 'JEE' },
  { subjectCode: 'CHE', name: 'Environmental Chemistry', number: 26, syllabusTag: 'JEE' },

  // ─── Mathematics — JEE ─────────────────────────────────────────────────────
  { subjectCode: 'MAT', name: 'Sets, Relations and Functions', number: 1, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Complex Numbers and Quadratic Equations', number: 2, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Matrices and Determinants', number: 3, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Permutations and Combinations', number: 4, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Mathematical Induction', number: 5, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Binomial Theorem and Its Applications', number: 6, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Sequences and Series', number: 7, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Limits, Continuity and Differentiability', number: 8, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Integral Calculus', number: 9, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Differential Equations', number: 10, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Coordinate Geometry', number: 11, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Three Dimensional Geometry', number: 12, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Vector Algebra', number: 13, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Statistics and Probability', number: 14, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Trigonometry', number: 15, syllabusTag: 'JEE' },
  { subjectCode: 'MAT', name: 'Mathematical Reasoning', number: 16, syllabusTag: 'JEE' },

  // ─── Physics — NEET ────────────────────────────────────────────────────────
  { subjectCode: 'PHY', name: 'Physical World and Measurement', number: 1, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Kinematics', number: 2, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Laws of Motion', number: 3, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Work, Energy and Power', number: 4, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Motion of System of Particles and Rigid Body', number: 5, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Gravitation', number: 6, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Properties of Bulk Matter', number: 7, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Thermodynamics', number: 8, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Behaviour of Perfect Gas and Kinetic Theory', number: 9, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Oscillations and Waves', number: 10, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Electrostatics', number: 11, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Current Electricity', number: 12, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Magnetic Effects of Current and Magnetism', number: 13, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Electromagnetic Induction and Alternating Currents', number: 14, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Electromagnetic Waves', number: 15, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Optics', number: 16, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Dual Nature of Matter and Radiation', number: 17, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Atoms and Nuclei', number: 18, syllabusTag: 'NEET' },
  { subjectCode: 'PHY', name: 'Electronic Devices', number: 19, syllabusTag: 'NEET' },

  // ─── Chemistry — NEET ──────────────────────────────────────────────────────
  { subjectCode: 'CHE', name: 'Some Basic Concepts of Chemistry', number: 1, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Structure of Atom', number: 2, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Classification of Elements and Periodicity in Properties', number: 3, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Chemical Bonding and Molecular Structure', number: 4, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'States of Matter', number: 5, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Thermodynamics', number: 6, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Equilibrium', number: 7, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Redox Reactions', number: 8, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Hydrogen', number: 9, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 's-Block Elements', number: 10, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'p-Block Elements', number: 11, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Organic Chemistry - Basic Principles and Techniques', number: 12, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Hydrocarbons', number: 13, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Environmental Chemistry', number: 14, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Solid State', number: 15, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Solutions', number: 16, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Electrochemistry', number: 17, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Chemical Kinetics', number: 18, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Surface Chemistry', number: 19, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'd and f Block Elements', number: 20, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Coordination Compounds', number: 21, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Haloalkanes and Haloarenes', number: 22, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Alcohols, Phenols and Ethers', number: 23, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Aldehydes, Ketones and Carboxylic Acids', number: 24, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Amines', number: 25, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Biomolecules', number: 26, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Polymers', number: 27, syllabusTag: 'NEET' },
  { subjectCode: 'CHE', name: 'Chemistry in Everyday Life', number: 28, syllabusTag: 'NEET' },

  // ─── Botany — NEET ─────────────────────────────────────────────────────────
  { subjectCode: 'BOT', name: 'The Living World', number: 1, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Biological Classification', number: 2, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Plant Kingdom', number: 3, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Morphology of Flowering Plants', number: 4, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Anatomy of Flowering Plants', number: 5, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Cell: The Unit of Life', number: 6, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Cell Cycle and Cell Division', number: 7, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Transport in Plants', number: 8, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Mineral Nutrition', number: 9, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Photosynthesis in Higher Plants', number: 10, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Respiration in Plants', number: 11, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Plant Growth and Development', number: 12, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Reproduction in Organisms', number: 13, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Sexual Reproduction in Flowering Plants', number: 14, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Principles of Inheritance and Variation', number: 15, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Molecular Basis of Inheritance', number: 16, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Evolution', number: 17, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Microbes in Human Welfare', number: 18, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Biotechnology - Principles and Processes', number: 19, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Biotechnology and its Applications', number: 20, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Organisms and Populations', number: 21, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Ecosystem', number: 22, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Biodiversity and Conservation', number: 23, syllabusTag: 'NEET' },
  { subjectCode: 'BOT', name: 'Environmental Issues', number: 24, syllabusTag: 'NEET' },

  // ─── Zoology — NEET ────────────────────────────────────────────────────────
  { subjectCode: 'ZOO', name: 'Animal Kingdom', number: 1, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Structural Organisation in Animals', number: 2, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Biomolecules', number: 3, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Digestion and Absorption', number: 4, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Breathing and Exchange of Gases', number: 5, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Body Fluids and Circulation', number: 6, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Excretory Products and their Elimination', number: 7, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Locomotion and Movement', number: 8, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Neural Control and Coordination', number: 9, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Chemical Coordination and Integration', number: 10, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Human Reproduction', number: 11, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Reproductive Health', number: 12, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Human Health and Disease', number: 13, syllabusTag: 'NEET' },
  { subjectCode: 'ZOO', name: 'Strategies for Enhancement in Food Production', number: 14, syllabusTag: 'NEET' },
];
